name: 'tpch_datavault'
version: '1.0'
config-version: 2

profile: 'tpch_datavault_profile'
model-paths: ["models"]
macro-paths: ["macros"]
models:
  tpch_datavault:
      staging:
        +materialized: view
        +database: DWH_SDG_DEMO
      raw_vault:
        +database: DWH_SDG_DEMO
      marts:
        +schema: DATA_MART


