version: 2
sources:
  - name: tpch_sf1kkkk
    database: SNOWFLAKE_SAMPLE_DATA  
    schema: TPCH_SF1  
    tables:      
     - name: customer      
     - name: orders      
     - name: lineitem

  - name: esquema_snapshot1    # nombre del esquema/logical source
    database: db_mytest        # opcional, si tu base de datos no es la default
    schema: sc_test            # esquema en Snowflake
    tables:
      - name: scd2_customers    # nombre de la tabla


models:
  - name: hub_customer
    description: "Hub de CUSTOMER"
    columns:      
      - name: c_custkey
        tests:          
          - not_null
          - unique