version: 2
sources:
  - name: tpch_sf1_nose
    database: SNOWFLAKE_SAMPLE_DATA  
    schema: TPCH_SF1  
    tables:      
     - name: customer      
     - name: orders      
     - name: lineitem

  - name: esquema_snapshot2       # nombre del esquema/logical source
    database: tpch_ag            # opcional, si tu base de datos no es la default
    schema: raw_vault           # esquema en Snowflake
    tables:
      - name: scd2_customers    # nombre de la tabla
