version: 2

sources:
  - name: stg_orders_date
    database: DWH_SDG_DEMO
    schema: raw_vault
    tables:
      - name: stg_orders
      
  - name: buv_calendar
    description: "Business vault for Calendar  table generated"

models:
  - name: buv_order_byline
    description: "Business vault for ORDER_BYLINE from raw_vault"
  
  - name: buv_customer
    description: "Business vault de CUSTOMER from raw_vault"
    columns:      
      - name: c_custid
        tests:          
          - not_null
         # - unique

  - name: buv_order_status
    description: "Business vault for ORDER_STATUS code & descriptions from raw_vault"


  - name: buv_customer_snap
    description: "Business vault de CUSTOMER from raw_vault_snapshots"
    columns:      
      - name: c_custid
        #tests:               # - not_null

          
